# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Dieses Problem wurde automatisch als veraltet markiert,
  da es in letzter Zeit keine Aktivit채t mehr gab.
  Es wird geschlossen, wenn keine weiteren Aktivit채ten stattfinden.
  
  Danke f체r Ihre Beitr채ge.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: true