language: php
php: 7.2.9
jobs:
  include:
    - stage: "LINT"
      script:
        - if find . -name "*.php" ! -path "./vendor/*" -exec php -l {} \; | grep -v "No syntax errors detected"; then exit 1; fi
    - stage: "Code Coverage"
      before_script:
        - curl -s http://getcomposer.org/installer | php
        - php composer.phar install -n
      script:
        - php vendor/bin/phpunit --coverage-clover build/coverage/xml
      after_script:
        - php vendor/bin/codacycoverage clover build/coverage/xml